export const RIFF_SET_ACCESS_TOKEN = 'RIFF_SET_ACCESS_TOKEN';
export const RIFF_SET_MEETING_ID = 'RIFF_SET_MEETING_ID';
export const RIFF_SET_MEETING_TITLE = 'RIFF_SET_MEETING_TITLE';
export const RIFF_SET_PARTICIPANT_ID = 'RIFF_SET_PARTICIPANT_ID';
