export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const UPDATE_DISPLAY_NAME = 'UPDATE_DISPLAY_NAME';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const MEETINGS_REQUEST = 'MEETINGS_REQUEST';
export const MEETINGS_SUCCESS = 'MEETINGS_SUCCESS';
export const MEETINGS_FAILURE = 'MEETINGS_FAILURE';
export const MEETING_RESET = 'MEETING_RESET';

export const MEETING_REQUEST = 'MEETING_REQUEST';
export const MEETING_SUCCESS = 'MEETING_SUCCESS';
export const MEETING_FAILURE = 'MEETING_FAILURE';

export const SCHEDULER_REQUEST = 'SCHEDULER_REQUEST';
export const SCHEDULER_SUCCESS = 'SCHEDULER_SUCCESS';
export const SCHEDULER_FAILURE = 'SCHEDULER_FAILURE';
export const SCHEDULER_RESET = 'SCHEDULER_RESET';

export const SET_RIFF_SERVER_ROOM_ID = 'SET_RIFF_SERVER_ROOM_ID';
export const RIFF_SERVER_AUTHENTICATE_SUCCESS = 'RIFF_SERVER_AUTHENTICATE_SUCCESS';
export const RIFF_SERVER_AUTHENTICATE_FAIL = 'RIFF_SERVER_AUTHENTICATE_FAIL';

export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';
export const RESET_HIDE_MESSAGE = 'RESET_HIDE_MESSAGE';

export const SET_MEETINGS_LIST_TYPE = 'SET_MEETINGS_LIST_TYPE';

export const UPDATE_SCHEDULER_REQUEST = 'UPDATE_SCHEDULER_REQUEST';
export const UPDATE_SCHEDULER_SUCCESS = 'UPDATE_SCHEDULER_SUCCESS';
export const UPDATE_SCHEDULER_FAILURE = 'UPDATE_SCHEDULER_FAILURE';
export const UPDATE_SCHEDULER_RESET = 'UPDATE_SCHEDULER_RESET';

export const DELETE_MEETINGS_REQUEST = 'DELETE_MEETINGS_REQUEST';
export const DELETE_MEETINGS_SUCCESS = 'DELETE_MEETINGS_SUCCESS';
export const DELETE_MEETINGS_FAILURE = 'DELETE_MEETINGS_FAILURE';

export const TOGGLE_MEETING_MEDIATOR = 'TOGGLE_MEETING_MEDIATOR';

export const LOC_RECORDING_ENGAGED = 'LOC_RECORDING_ENGAGED';
export const LOC_RECORDING_STATS = 'LOC_RECORDING_STATS';
export const LOC_RECORDING_SET_SHARED_VIDEO_ID = 'LOC_RECORDING_SET_SHARED_VIDEO_ID';

export const PERSONAL_MEETING_REQUEST = 'PERSONAL_MEETING_REQUEST';
export const PERSONAL_MEETING_SUCCESS = 'PERSONAL_MEETING_SUCCESS';
export const PERSONAL_MEETING_FAILURE = 'PERSONAL_MEETING_FAILURE';


export const CALENDAR_SET_GOOGLE_API_STATE = 'CALENDAR_SET_GOOGLE_API_STATE';
export const CALENDAR_CLEAR_GOOGLE_INTEGRATION = 'CALENDAR_CLEAR_GOOGLE_INTEGRATION';
export const CALENDAR_SET_GOOGLE_ERROR = 'CALENDAR_SET_GOOGLE_ERROR';
export const CALENDAR_SET_GOOGLE_INTEGRATION = 'CALENDAR_SET_GOOGLE_INTEGRATION';
export const CALENDAR_SET_GOOGLE_API_PROFILE = 'CALENDAR_SET_GOOGLE_API_PROFILE';

export const CALENDAR_SET_MS_AUTH_STATE = 'CALENDAR_SET_MS_AUTH_STATE';
export const CALENDAR_CLEAR_MS_INTEGRATION = 'CALENDAR_CLEAR_MS_INTEGRATION';
export const CALENDAR_SET_MS_INTEGRATION = 'CALENDAR_SET_MS_INTEGRATION';
export const CALENDAR_SET_MS_ERROR = 'CALENDAR_SET_MS_ERROR';
