name: Simple CI

on:
  pull_request:
  push:
    branches:
      - develop
      - riff-master
      - 'release/*'

jobs:
  run-ci:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/

      - uses: actions/checkout@v2

      - name: Install dependencies based on package-lock.json
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_PRIVATE_READ_TOKEN }}

      - run: npm run lint

      - run: make
