name: Simple CI

on:
  pull_request:
  push:
    branches:
      - 'riff/mods_*'

jobs:
  run-ci:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/

      - uses: actions/checkout@v2

      - name: Install dependencies based on package-lock.json
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_PRIVATE_READ_TOKEN }}

      - run: make lint

      - run: make all
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
