name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies based on package-lock.json
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_PRIVATE_READ_TOKEN }}

      - name: Build and pack the production configuration
        id: build-package
        run: |
          make prod-package
          echo "PKG_NAME=$(ls *-prod.tar.bz2)" >> $GITHUB_OUTPUT
          # Until action/checkout supports getting the tags on the commit w/o having to get the whole repo this is commented out
          # git tag -l --format='%(contents:lines=100)' ${GITHUB_REF#refs/*/} > ./RELEASE_BODY.txt
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_PRIVATE_READ_TOKEN }}
          NODE_OPTIONS: '--max-old-space-size=5120'
          TERM: dumb

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          # See commented out code above which would create this body file
          # bodyFile: ./RELEASE_BODY.txt
          generateReleaseNotes: true
          draft: false
          prerelease: false
          artifacts: ./${{ steps.build-package.outputs.PKG_NAME }}
          artifactContentType: application/x-tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
